INSERT INTO teams VALUES (NULL,'Arizona Cardinals','cards.png');
INSERT INTO teams VALUES (NULL,'Atlanta Falcons','falcs.png');
INSERT INTO teams VALUES (NULL,'Baltimore Ravens','ravens.png');
INSERT INTO teams VALUES (NULL,'Buffalo Bills','bills.png');
INSERT INTO teams VALUES (NULL,'Carolina Panthers','cats.png');
INSERT INTO teams VALUES (NULL,'Chicago Bears','bears.png');
INSERT INTO teams VALUES (NULL,'Cincinnati Bengals','bengals.png');
INSERT INTO teams VALUES (NULL,'Cleveland Browns','browns.png');
INSERT INTO teams VALUES (NULL,'Dallas Cowboys','boys.png');
INSERT INTO teams VALUES (NULL,'Denver Broncos','broncos.png');
INSERT INTO teams VALUES (NULL,'Detroit Lions','lions.png');
INSERT INTO teams VALUES (NULL,'Green Bay Packers','pack.png');
INSERT INTO teams VALUES (NULL,'Houston Texans','texans.png');
INSERT INTO teams VALUES (NULL,'Indianapolis Colts','colts.png');
INSERT INTO teams VALUES (NULL,'Jacksonville Jaguars','jags.png');
INSERT INTO teams VALUES (NULL,'Kansas City Chiefs','chiefs.png');
INSERT INTO teams VALUES (NULL,'Los Angeles Chargers','chargers.png');
INSERT INTO teams VALUES (NULL,'Los Angeles Rams','rams.png');
INSERT INTO teams VALUES (NULL,'Miami Dolphins','dolphins.png');
INSERT INTO teams VALUES (NULL,'Minnesota Vikings','vikings.png');
INSERT INTO teams VALUES (NULL,'New England Patriots','pats.png');
INSERT INTO teams VALUES (NULL,'New Orleans Saints','saints.png');
INSERT INTO teams VALUES (NULL,'New York Giants','giants.png');
INSERT INTO teams VALUES (NULL,'New York Jets','jets.png');
INSERT INTO teams VALUES (NULL,'Oakland Raiders','raiders.png');
INSERT INTO teams VALUES (NULL,'Philadelphia Eagles','eagles.png');
INSERT INTO teams VALUES (NULL,'Pittsburgh Steelers','steelers.png');
INSERT INTO teams VALUES (NULL,'San Francisco 49ers','niners.png');
INSERT INTO teams VALUES (NULL,'Seattle Seahawks','hawks.png');
INSERT INTO teams VALUES (NULL,'Tampa Bay Buccaneers','bucs.png');
INSERT INTO teams VALUES (NULL,'Tennessee Titans','titans.png');
INSERT INTO teams VALUES (NULL,'Washington Redskins','skins.png');